// Auto-generated by InSpatial Serve – DO NOT EDIT
// This file is regenerated on each build when extensions change
declare global {
  namespace InSpatial {
    interface ExtensionTriggers { }
  }
}
export {};
